### PR TITLE
Fix java.util.Map.get(Object) is null

### PR DESCRIPTION
**Pull request by sgjava**
We discussed this a bit back, but you fix causes a NPE. Make any changes you see fit.
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at com.codeferm.app.PlayUI.onChange(PlayUI.java:133)
	at de.milchreis.uibooster.model.formelements.SelectionFormElement.lambda$createComponent$0(SelectionFormElement.java:25)
```

### CODE REVIEW

**Comment by Milchreis** [comment]
Hi Steven,

thank you very much for your PR. It's very nice of you for working on the code 😊
Could you add your code here, which raises the NPE? It's because I can not reproduce the bug.

EarIier, I wrote a test for this method and this works for me: [Look here](https://github.com/Milchreis/UiBooster/blob/master/src/test/java/de/milchreis/uibooster/FormBuilderTest.java#L252)

**Comment by sgjava** [comment]
```
                refresh();
                final var selection = form.getById("events").toSelection();
                selection.setPossibilities(elements);

    /**
     * Refresh from database.
     */
    public void refresh() {
        buffers = play.loadBuffers();
        images = play.loadEvents();
        elements = new ArrayList<>();
        timestamps = new HashMap<>();
        var i = 0;
        // Build Map of timestamps to image index.
        for (final var image : images) {
            timestamps.put(play.formatTimestamp(image.get(0).getEventTime()), i++);
        }
        // Build list of timestamps
        for (i = images.size(); i-- > 0;) {
            elements.add(play.formatTimestamp(images.get(i).get(0).getEventTime()));
        }
        index = images.size() - 1;
    }
```

**Comment by Milchreis** [comment]
hi steven,

last week I had very less time. Today I tried to write a test case to get the error, but it's working for me. I tried to reproduce the scenario by your code snippet. Could you try the following code?

```java
private List<String> elements = new ArrayList<>();

@Test
public void test_form_change_possibilities2() throws InterruptedException {
    final Form form = booster.createForm("Personal information")
            .addSelection("What are your favorite snacks?", elements)
            .run();

    Thread.sleep(3000);

    refresh();

    form.getByIndex(0)
            .toSelection()
            .setPossibilities(elements);

    Thread.sleep(10000);
}

public void refresh() {
    elements = new ArrayList<>();

    for (int i = 0; i < 10000; i++)
        elements.add("some string " + (i + 1));
}
```

I don't really understand why your fix works, because the NPE is thrown in line 25 of `SelectionFormElement.java`. This is the creation state and `setPossibilities()` is not called.

**Comment by sgjava** [comment]
This seems to work. My code is much more complex, so let me see where it is on my side.
```
package com.codeferm.uitest;

import de.milchreis.uibooster.UiBooster;
import de.milchreis.uibooster.model.Form;
import de.milchreis.uibooster.model.FormElement;
import de.milchreis.uibooster.model.FormElementChangeListener;
import de.milchreis.uibooster.model.UiBoosterOptions;
import java.util.Arrays;
import java.util.List;

public class Selection implements FormElementChangeListener {

    private List<String> elements;
    private final UiBooster booster;

    public Selection() {
        booster = new UiBooster(UiBoosterOptions.Theme.SWING);
        elements = Arrays.asList(new String[]{"one", "two", "three"});
    }

    public void build() {
        booster.createForm("Selection").
                addSelection("Events", elements).setID("events").
                setChangeListener(this).show();
    }

    @Override
    public void onChange(final FormElement fe, final Object o, final Form form) {
        switch (fe.getId()) {
            case "events" -> {
                elements = Arrays.asList(new String[]{"four", "five", "six"});
                final var selection = form.getById("events").toSelection();
                selection.setPossibilities(elements);
            }
            default -> booster.showErrorDialog(String.format("%s onChange not handled", fe.getId()), "Error");
        }
    }

    public static void main(String[] args) {
        final var app = new Selection();
        app.build();
    }
}
```

**Comment by sgjava** [comment]
@Milchreis I think I see whats going on. It appears setPossibilities is calling onChange somehow. What I do is have a refresh button to refresh the list from the database. After setPossibilities is looks like the onChange is called again and for whatever reason the list is null. If I allow it to skip the selection logic it will update. Just looks like I have crazy onChange going on.

**Comment by sgjava** [comment]
Here's the fix (note isEmpty check in  case "events"). So there's an onChange caused by setPossibilities before the selection UI is updated.
```
    @Override
    public void onChange(final FormElement fe, final Object o, final Form form) {
        final var label = (JLabel) form.getById("image").getValue();
        switch (fe.getId()) {
            case "play":
                final var bufferStart = buffers.get(images.get(index).get(0).getEventData()).getEventTime().toInstant();
                final var motionStart = images.get(index).get(0).getEventTime().toInstant();
                final var motionStop = images.get(index).get(2).getEventTime().toInstant();
                final var start = Duration.between(bufferStart, motionStart);
                final var duration = Duration.between(motionStart, motionStop);
                final var fileName = images.get(index).get(0).getEventData().replace(remoteFromPath, remoteToPath);
                play(fileName, start.getSeconds(), duration.getSeconds());
                break;
            case "events":
                final var value = (String) form.getById("events").getValue();
                // This will happen when Refresh pressed bacause selection list is updated
                if (!StringUtils.isEmpty(value)) {
                    index = timestamps.get(value);
                    label.setIcon(new ImageIcon(images.get(index).get(1).getEventData().replace(remoteFromPath, remoteToPath)));
                }
                break;
            case "refresh":
                refresh();
                final var selection = form.getById("events").toSelection();
                selection.setPossibilities(elements);
                break;
            default:
                booster.showErrorDialog(String.format("%s onChange not handled", fe.getId()), "Error");
        }
        update(form);
    }
```

**Pull request closed without merging**
